# ruff: noqa: E501
"""Compatibility audit across every country and quarter in the harmonized panel.

    python scripts/26_compatibility_check.py [--drift-pp 3.0]

Writes output/tables/compat_profile.csv (one row per country-quarter),
compat_flags.csv (level problems and quarter-to-quarter jumps),
compat_coverage.csv (window, gaps, depth per country),
compat_availability.csv (share of rows with each variable filled) and
compat_drift.csv (weighted category shares with drift flags, all countries),
and a Markdown summary in docs/compatibility.md.
"""

from __future__ import annotations

import argparse
from datetime import date

import pandas as pd

from lfspanel.codebook import distribution_drift
from lfspanel.compat import (
    availability_table,
    coverage_table,
    flag_profile,
    quarter_profile,
)
from lfspanel.config import OUTPUT, ROOT
from lfspanel.store import duckdb_connect


def _md(df: pd.DataFrame, cols=None) -> str:
    d = df if cols is None else df[cols]
    lines = ["| " + " | ".join(d.columns) + " |", "|" + "---|" * len(d.columns)]
    for _, r in d.iterrows():
        lines.append("| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--drift-pp", type=float, default=3.0)
    args = ap.parse_args()
    con = duckdb_connect(read_only=True)
    tables = OUTPUT / "tables"
    tables.mkdir(parents=True, exist_ok=True)

    prof = quarter_profile(con)
    prof.round(3).to_csv(tables / "compat_profile.csv", index=False)
    flags = flag_profile(prof)
    flags.to_csv(tables / "compat_flags.csv", index=False)
    cov = coverage_table(prof)
    cov.to_csv(tables / "compat_coverage.csv", index=False)
    avail = availability_table(con)
    avail.to_csv(tables / "compat_availability.csv", index=False)
    drift = distribution_drift(con, threshold_pp=args.drift_pp)
    drift.to_csv(tables / "compat_drift.csv", index=False)
    has_flag = drift["flag"].fillna("").astype(str).str.len().gt(0)
    flagged_drift = drift[has_flag] if "flag" in drift else drift.iloc[0:0]

    levels = flags[flags["kind"] == "level"]
    jumps = flags[flags["kind"] == "jump"]
    doc = [
        f"# Compatibility audit ({date.today().isoformat()})",
        "",
        "Generated by `scripts/26_compatibility_check.py` over every partition in",
        "`data/processed/harmonized`. Tables: `output/tables/compat_*.csv`.",
        "",
        "## Coverage",
        "",
        _md(cov),
        "",
        "## Variable availability (% of persons of working age, or of the employed for job variables)",
        "",
        _md(avail),
        "",
        f"## Level problems ({len(levels)} rows)",
        "",
        _md(levels, ["countrycode", "period", "metric", "value", "threshold", "issue"]) if len(levels) else "None.",
        "",
        f"## Quarter-to-quarter jumps ({len(jumps)} rows)",
        "",
        _md(jumps, ["countrycode", "period", "metric", "previous", "value", "change", "issue"]) if len(jumps) else "None.",
        "",
        f"## Distribution drift, all countries ({len(flagged_drift)} flagged shares, threshold {args.drift_pp} pts)",
        "",
        _md(flagged_drift.round(2)) if len(flagged_drift) else "None.",
        "",
    ]  # fmt: skip
    (ROOT / "docs" / "compatibility.md").write_text("\n".join(doc))
    with pd.option_context("display.width", 220, "display.max_rows", 500):
        print(cov.to_string(index=False))
        print(
            f"\n{len(levels)} level problems, {len(jumps)} jumps, {len(flagged_drift)} drift flags"
        )
        print(flags.to_string(index=False))
    print(f"-> {ROOT / 'docs' / 'compatibility.md'}")


if __name__ == "__main__":
    main()
